parameters:
  - name: Reason
    displayName: "Reason for triggering the pipeline run"
    type: string
    default: "Testing Azure Policies..."

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - ".github/workflows/**"
      - "policies/**"
      - "tests/**"

pool:
  vmImage: "windows-latest"

steps:
  - checkout: self
    displayName: Checkout repository
  - pwsh: |
      $password = ConvertTo-SecureString $env:AZURE_SUBSCRIPTION_CLIENT_SECRET -AsPlainText -Force
      $credential =  New-Object System.Management.Automation.PSCredential("$(AZURE_SUBSCRIPTION_CLIENT_ID)", $password)
      Connect-AzAccount -Subscription "$(AZURE_SUBSCRIPTION_ID)" -Tenant "$(AZURE_SUBSCRIPTION_TENANT_ID)" -ServicePrincipal -Credential $credential -Scope CurrentUser
    displayName: Login to Azure
    env:
      AZURE_SUBSCRIPTION_CLIENT_SECRET: $(AZURE_SUBSCRIPTION_CLIENT_SECRET)
    
  
    