parameters:
  - name: Reason
    displayName: "Reason for triggering the pipeline run"
    type: string
    default: "Testing Azure Policies..."

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - ".github/workflows/**"
      - "policies/**"
      - "tests/**"

pool:
  vmImage: "windows-latest"

steps:
  - checkout: self
    displayName: Checkout repository
  - pwsh: |
      Install-Module -Name 'Az' -RequiredVersion '4.7.0' -Force -Scope CurrentUser -ErrorAction Stop
    workingDirectory: $(Build.SourcesDirectory)
    displayName: Install PowerShell modules
    